// Curated Lingo vocabulary for completions + hover. The parser in the runtime
// matches these structurally (case-insensitive), so this list is what the LSP
// exposes; the server ALSO pulls every builtin name from the runtime's
// builtin table, so that list is always complete even when this file lags.

export interface DocEntry {
  name: string;
  doc: string;
  kind: 'keyword' | 'function' | 'property' | 'constant';
}

export const KEYWORDS: DocEntry[] = [
  { name: 'if', doc: 'Conditional: `if <cond> then ... end if` (one-liner or block).', kind: 'keyword' },
  { name: 'then', doc: 'Separates the condition from the body in an `if`.', kind: 'keyword' },
  { name: 'else', doc: 'Alternative branch of an `if`.', kind: 'keyword' },
  { name: 'end', doc: 'Closes a block: `end if`, `end repeat`, `end case`, `end on`.', kind: 'keyword' },
  { name: 'case', doc: 'Multi-branch switch: `case x of ... end case`.', kind: 'keyword' },
  { name: 'otherwise', doc: 'Default branch of a `case` statement.', kind: 'keyword' },
  { name: 'repeat', doc: 'Loop: `repeat with i = a to b`, `repeat with x in list`, `repeat while cond`.', kind: 'keyword' },
  { name: 'with', doc: '`repeat with` counter/in-list form.', kind: 'keyword' },
  { name: 'in', doc: '`repeat with x in <list>` — or `x in <chunk>` membership test.', kind: 'keyword' },
  { name: 'while', doc: '`repeat while <cond>` — loop until the condition is false.', kind: 'keyword' },
  { name: 'exit', doc: 'Leave the current handler (`exit`) or loop (`exit repeat`).', kind: 'keyword' },
  { name: 'next', doc: 'Skip to the next iteration of the innermost `repeat` (`next repeat`).', kind: 'keyword' },
  { name: 'return', doc: 'Exit the handler, optionally returning a value.', kind: 'keyword' },
  { name: 'put', doc: 'Print/assign: `put <val>` or `put <val> into|after|before <target>`.', kind: 'keyword' },
  { name: 'into', doc: '`put ... into <var>` — replace the target entirely.', kind: 'keyword' },
  { name: 'after', doc: '`put ... after <chunk>` — append at the end of the target.', kind: 'keyword' },
  { name: 'before', doc: '`put ... before <chunk>` — insert at the start of the target.', kind: 'keyword' },
  { name: 'delete', doc: 'Remove a chunk: `delete <chunkExpr>` (e.g. `delete word 1 of tLine`).', kind: 'keyword' },
  { name: 'set', doc: 'Assignment: `set <target> = <value>` (or `set <target> to ...`).', kind: 'keyword' },
  { name: 'to', doc: '`set ... to <value>` / `repeat with i = a to b` range end.', kind: 'keyword' },
  { name: 'global', doc: 'Declares a global variable for the rest of the handler.', kind: 'keyword' },
  { name: 'go', doc: 'Move the playhead: `go to frame X`, `go to movie "..."`, `go the frame`.', kind: 'keyword' },
  { name: 'on', doc: 'Defines a handler: `on <name> [params] ... end`.', kind: 'keyword' },
  { name: 'not', doc: 'Logical negation: `not <bool>`.', kind: 'keyword' },
  { name: 'and', doc: 'Logical AND (also `&` string concat in some dialects).', kind: 'keyword' },
  { name: 'or', doc: 'Logical OR.', kind: 'keyword' },
  { name: 'mod', doc: 'Modulo: `a mod b` — remainder, sign follows the dividend.', kind: 'keyword' },
  { name: 'the', doc: 'Property access: `the <prop> [of <obj>]` — e.g. `the mouseLoc`, `the locH of sprite 5`.', kind: 'keyword' },
  { name: 'of', doc: '`the <prop> of <obj>` / `word 1 of tLine` — member access.', kind: 'keyword' },
  { name: 'new', doc: 'Constructor call: `script("X").new(...)` (also `new(#kind)`).', kind: 'keyword' },
  { name: 'me', doc: 'The current script instance (like `this`).', kind: 'keyword' },
  { name: 'down', doc: '`repeat with i = a down to b` — count downwards.', kind: 'keyword' },
  { name: 'char', doc: 'Chunk type: `char 1 of tStr`.', kind: 'keyword' },
  { name: 'word', doc: 'Chunk type: `word 2 of tStr` (space-delimited).', kind: 'keyword' },
  { name: 'line', doc: 'Chunk type: `line 1 of tStr` (newline-delimited).', kind: 'keyword' },
  { name: 'item', doc: 'Chunk type: `item 3 of tStr` (comma-delimited).', kind: 'keyword' },
  { name: 'paragraph', doc: 'Chunk type: paragraph of a text member.', kind: 'keyword' },
];

export const CONSTANTS: DocEntry[] = [
  { name: 'TRUE', doc: 'The boolean true (also 1).', kind: 'constant' },
  { name: 'FALSE', doc: 'The boolean false (also 0).', kind: 'constant' },
  { name: 'VOID', doc: 'The empty value (also #void).', kind: 'constant' },
  { name: 'PI', doc: '3.14159265…', kind: 'constant' },
  { name: 'E', doc: '2.71828182… (natural log base).', kind: 'constant' },
];

// Common `the X` properties. Hover + completion after `the `.
export const THE_PROPS: DocEntry[] = [
  { name: 'mouseLoc', doc: 'The mouse position as a point.', kind: 'property' },
  { name: 'mouseH', doc: 'Horizontal mouse position.', kind: 'property' },
  { name: 'mouseV', doc: 'Vertical mouse position.', kind: 'property' },
  { name: 'mouseDown', doc: 'TRUE while the mouse button is held.', kind: 'property' },
  { name: 'mouseUp', doc: 'TRUE while the mouse button is released.', kind: 'property' },
  { name: 'clickLoc', doc: 'Where the last click happened (point).', kind: 'property' },
  { name: 'clickOn', doc: 'The last sprite that received a mouseDown (sprite ref).', kind: 'property' },
  { name: 'key', doc: 'The last key pressed as a string.', kind: 'property' },
  { name: 'keyCode', doc: 'Numeric code of the last key pressed.', kind: 'property' },
  { name: 'keyDown', doc: 'TRUE while a key is held.', kind: 'property' },
  { name: 'stillDown', doc: 'TRUE when the mouse button stays down after mouseDown.', kind: 'property' },
  { name: 'shiftDown', doc: 'TRUE while Shift is held.', kind: 'property' },
  { name: 'controlDown', doc: 'TRUE while Ctrl is held.', kind: 'property' },
  { name: 'optionDown', doc: 'TRUE while Alt/Option is held.', kind: 'property' },
  { name: 'commandDown', doc: 'TRUE while Cmd/Ctrl is held.', kind: 'property' },
  { name: 'doubleClick', doc: 'TRUE on the second press of a double-click.', kind: 'property' },
  { name: 'frame', doc: 'The current frame number of the movie.', kind: 'property' },
  { name: 'frameLabel', doc: 'The label of the current frame.', kind: 'property' },
  { name: 'frameRate', doc: 'Frames per second the movie plays at.', kind: 'property' },
  { name: 'tempo', doc: 'Playback tempo in ms per frame.', kind: 'property' },
  { name: 'timer', doc: 'Milliseconds since the movie started (or startTimer()).', kind: 'property' },
  { name: 'ticks', doc: '60ths of a second since the movie started.', kind: 'property' },
  { name: 'milliseconds', doc: 'Milliseconds since the movie started.', kind: 'property' },
  { name: 'date', doc: 'The current date as a string.', kind: 'property' },
  { name: 'time', doc: 'The current time as a string.', kind: 'property' },
  { name: 'day', doc: 'Day of the month (1-31).', kind: 'property' },
  { name: 'month', doc: 'Month name.', kind: 'property' },
  { name: 'year', doc: 'The current year.', kind: 'property' },
  { name: 'moviePath', doc: 'URL path of the running movie.', kind: 'property' },
  { name: 'movieName', doc: 'Name of the running movie.', kind: 'property' },
  { name: 'movieFile', doc: 'File path of the running movie.', kind: 'property' },
  { name: 'movieTime', doc: 'Milliseconds the movie has been playing.', kind: 'property' },
  { name: 'soundEnabled', doc: 'TRUE when sound output is on.', kind: 'property' },
  { name: 'beepOn', doc: 'TRUE when beep() is audible.', kind: 'property' },
  { name: 'floatPrecision', doc: 'Decimal places used when float->string.', kind: 'property' },
  { name: 'colorDepth', doc: 'Bits per pixel of the stage.', kind: 'property' },
  { name: 'exitLock', doc: 'TRUE blocks the user from closing the player.', kind: 'property' },
  { name: 'idleHandlerPeriod', doc: 'Seconds between idle handler calls.', kind: 'property' },
  { name: 'loc', doc: 'Sprite/member position as a point.', kind: 'property' },
  { name: 'locH', doc: 'Horizontal position (sprite/member).', kind: 'property' },
  { name: 'locV', doc: 'Vertical position (sprite/member).', kind: 'property' },
  { name: 'width', doc: 'Width in pixels.', kind: 'property' },
  { name: 'height', doc: 'Height in pixels.', kind: 'property' },
  { name: 'regpoint', doc: 'Registration point of a bitmap member.', kind: 'property' },
  { name: 'rotation', doc: 'Rotation angle of a sprite.', kind: 'property' },
  { name: 'flipH', doc: 'TRUE flips the sprite horizontally.', kind: 'property' },
  { name: 'flipV', doc: 'TRUE flips the sprite vertically.', kind: 'property' },
  { name: 'ink', doc: 'Ink effect of a sprite (0-36).', kind: 'property' },
  { name: 'blend', doc: 'Blend percentage (0-100) of a sprite.', kind: 'property' },
  { name: 'visible', doc: 'TRUE shows the sprite.', kind: 'property' },
  { name: 'member', doc: 'The member of a sprite.', kind: 'property' },
  { name: 'castNum', doc: 'Member number within its castLib.', kind: 'property' },
  { name: 'castLibNum', doc: 'CastLib number of a member.', kind: 'property' },
  { name: 'scriptNum', doc: 'Script member number of a sprite.', kind: 'property' },
  { name: 'puppet', doc: 'TRUE = the movie script controls the sprite.', kind: 'property' },
  { name: 'constraint', doc: 'Sprite whose rect confines this sprite.', kind: 'property' },
  { name: 'name', doc: 'The name of the member/object.', kind: 'property' },
  { name: 'number', doc: 'The number of a member/castLib.', kind: 'property' },
  { name: 'type', doc: 'The type of a member (media type).', kind: 'property' },
  { name: 'text', doc: 'The text of a text/field member.', kind: 'property' },
  { name: 'color', doc: 'Foreground color of a text member.', kind: 'property' },
  { name: 'bgColor', doc: 'Background color of a text member.', kind: 'property' },
  { name: 'hiliteColor', doc: 'Highlight color of a field member.', kind: 'property' },
  { name: 'palette', doc: 'Palette of a bitmap member.', kind: 'property' },
  { name: 'rect', doc: 'Bounding rect of a member/sprite.', kind: 'property' },
  { name: 'top', doc: 'Top edge of a rect.', kind: 'property' },
  { name: 'left', doc: 'Left edge of a rect.', kind: 'property' },
  { name: 'bottom', doc: 'Bottom edge of a rect.', kind: 'property' },
  { name: 'right', doc: 'Right edge of a rect.', kind: 'property' },
  { name: 'font', doc: 'Font name of a text member.', kind: 'property' },
  { name: 'fontSize', doc: 'Font size in points.', kind: 'property' },
  { name: 'fontStyle', doc: 'Font style (bold, italic, underline…).', kind: 'property' },
  { name: 'lineHeight', doc: 'Line height of a text member.', kind: 'property' },
  { name: 'alignment', doc: 'Text alignment (left/center/right).', kind: 'property' },
  { name: 'wordWrap', doc: 'TRUE wraps long lines in a field.', kind: 'property' },
  { name: 'editable', doc: 'TRUE allows typing in a field member.', kind: 'property' },
  { name: 'boxType', doc: 'Field box type (#adjust, #fixed, #scroll).', kind: 'property' },
  { name: 'autoTab', doc: 'TRUE tabs to the next field at the edge.', kind: 'property' },
  { name: 'spriteNum', doc: 'The channel number of a sprite.', kind: 'property' },
  { name: 'foreColor', doc: 'Foreground color index.', kind: 'property' },
  { name: 'backColor', doc: 'Background color index.', kind: 'property' },
  { name: 'castLib', doc: 'CastLib ref of a member.', kind: 'property' },
];

// One-liners for the builtins the corpus actually uses; hover falls back to a
// generic note for the rest (names come from the runtime builtin table).
export const BUILTIN_DOCS: Record<string, string> = {
  abs: 'Absolute value.',
  sqrt: 'Square root (float-typed result).',
  sqr: 'Square: x * x.',
  power: 'x raised to y.',
  integer: 'Truncate toward zero to an integer.',
  float: 'Convert to a float.',
  value: 'Parse a string as a Lingo expression.',
  string: 'Convert a value to its string form.',
  length: 'Character count of a string.',
  min: 'Smallest of the arguments.',
  max: 'Largest of the arguments.',
  random: 'Random integer 1..n (seeded by randomSeed).',
  randomSeed: 'Seed for the random number generator.',
  sin: 'Sine of an angle in radians.',
  cos: 'Cosine of an angle in radians.',
  tan: 'Tangent of an angle in radians.',
  atan: 'Arctangent (radians).',
  ln: 'Natural logarithm.',
  log: 'Logarithm base 10.',
  exp: 'e raised to x.',
  round: 'Round to nearest integer (halves away from zero).',
  trunc: 'Truncate toward zero.',
  charToNum: 'ASCII code of the first character.',
  numToChar: 'Character for an ASCII code.',
  offset: 'Position of the first occurrence of a substring.',
  contains: 'TRUE when the string contains the substring.',
  starts: 'TRUE when the string starts with the prefix.',
  ends: 'TRUE when the string ends with the suffix.',
  chunkCount: 'Number of chunks (chars/words/lines/items).',
  count: 'Number of items in a list or chunks in a string.',
  list: 'Build a linear list from the arguments.',
  propList: 'Build a property list from the arguments.',
  add: 'Add a value to a list (unique).',
  addAt: 'Insert a value at a list position.',
  append: 'Append a value to a list.',
  deleteAt: 'Remove the item at a list position.',
  deleteOne: 'Remove the first matching value from a list.',
  getAt: 'The item at a list position.',
  getOne: 'The first position holding the value.',
  getPos: 'The position of a value in a list.',
  getProp: 'Value of a proplist key.',
  getPropAt: 'Value at a proplist position.',
  getaProp: 'Value of a proplist key (or VOID).',
  setAt: 'Replace the item at a list position.',
  setProp: 'Set a proplist key.',
  setaProp: 'Set a proplist key (creates if missing).',
  duplicate: 'Deep copy of a value.',
  ilk: 'Type of a value: #list, #string, #integer…',
  listP: 'TRUE when the value is a list.',
  stringP: 'TRUE when the value is a string.',
  integerP: 'TRUE when the value is an integer.',
  floatP: 'TRUE when the value is a float.',
  objectP: 'TRUE when the value is an object.',
  voidP: 'TRUE when the value is VOID.',
  symbolP: 'TRUE when the value is a symbol.',
  point: 'Build a point(x, y).',
  rect: 'Build a rect(l, t, r, b).',
  color: 'Build a color from RGB values.',
  rgb: 'Build a color from red/green/blue.',
  paletteIndex: 'RGB color at an index of the current palette.',
  image: 'Create a new image(width, height, depth).',
  copyPixels: 'Copy pixels between images (with ink/blend/mask).',
  fill: 'Fill an image rect with a color.',
  setPixel: 'Set one pixel of an image.',
  getPixel: 'Read one pixel of an image.',
  createMask: 'Create an ink-9 mask image from the opaque pixels.',
  puppetsprite: 'Mark a channel as script-controlled.',
  puppettempo: 'Set the playback tempo from script.',
  puppetsound: 'Play a sound member on a channel.',
  puppetpalette: 'Control the palette from script.',
  startTimer: 'Reset `the timer` to zero.',
  rollover: 'The sprite number under the mouse (0 when none).',
  keyPressed: 'TRUE while the given key is held.',
  beep: 'Play the system beep.',
  alert: 'Show an alert dialog with the message.',
  member: 'Look up a cast member by name/number.',
  script: 'Look up a script member.',
  sprite: 'Look up a sprite by channel.',
  castlib: 'Look up a castLib by name/number.',
  window: 'Look up an MIAW window by id.',
  timeout: 'Create a timeout object (`.new(period, handler, target)`).',
  xtra: 'Create an Xtra instance by name.',
  new: 'Constructor: `script("X").new(...)`.',
  getpref: 'Read a preference string.',
  setpref: 'Write a preference string.',
  externalParamValue: 'Value of an external parameter (embed tag).',
  externalParamCount: 'Number of external parameters.',
  externalParamName: 'Name of an external parameter.',
  netID: 'Net ID of the current connection.',
  netDone: 'TRUE when a net request finished.',
  netError: 'Error string of a net request.',
  netTextResult: 'Text result of a net request.',
  netLastModDate: 'Last-modified date of a net request.',
  preloadNetThing: 'Preload a URL into the cache.',
  importFileInto: 'Import a media file into a member.',
  getNetText: 'Fetch a URL as text (returns a net id).',
  playFile: 'Play a sound file.',
  closeXlib: 'Close an Xtra library.',
  openXlib: 'Open an Xtra library.',
  showXlib: 'List loaded Xtra libraries.',
};
